#!/usr/bin/env python3
"""Convert After Dark flying-toaster GIFs (references/toasters/) to toaster_sprites.h.

Sprites: github.com/bryanbraun/after-dark-css (artwork (c) Berkeley Systems).
Run from repo root: python3 tools/toaster_convert.py
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "references" / "toasters"
OUT = ROOT / "toaster_sprites.h"

SPRITE_W = SPRITE_H = 64
TRANSPARENT = 0xF81F  # magenta sentinel; asserted absent from real pixels


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def frame_to_565(im):
    """RGBA 64x64 frame -> list of uint16, transparent px = TRANSPARENT."""
    out = []
    for r, g, b, a in im.getdata():
        if a < 128:
            out.append(TRANSPARENT)
        else:
            v = rgb565(r, g, b)
            assert v != TRANSPARENT, "real pixel collides with transparent key"
            out.append(v)
    return out


def emit(f, name, frames):
    f.write(f"static const uint16_t {name}[{len(frames)}][{SPRITE_W * SPRITE_H}] = {{\n")
    for fr in frames:
        f.write("  {\n")
        for i in range(0, len(fr), 16):
            f.write("    " + ", ".join(f"0x{v:04X}" for v in fr[i : i + 16]) + ",\n")
        f.write("  },\n")
    f.write("};\n\n")


def main():
    sheet = Image.open(SRC / "toaster-sprite.gif").convert("RGBA")
    assert sheet.size == (256, 64), sheet.size
    toaster = [frame_to_565(sheet.crop((i * 64, 0, (i + 1) * 64, 64))) for i in range(4)]
    toast = [frame_to_565(Image.open(SRC / f"toast{i}.gif").convert("RGBA")) for i in range(4)]

    with OUT.open("w") as f:
        f.write("// Generated by tools/toaster_convert.py -- do not edit.\n")
        f.write("// After Dark flying toaster sprites, artwork (c) Berkeley Systems.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define TOASTER_SPRITE_W {SPRITE_W}\n#define TOASTER_SPRITE_H {SPRITE_H}\n")
        f.write(f"#define TOASTER_TRANSPARENT 0x{TRANSPARENT:04X}\n\n")
        emit(f, "kToasterFrames", toaster)
        emit(f, "kToastFrames", toast)

    # contact sheet for eyeballing
    proof = Image.new("RGB", (64 * 4, 64 * 2), (32, 32, 32))
    for i, fr in enumerate(toaster + toast):
        img = Image.new("RGB", (64, 64), (32, 32, 32))
        img.putdata([(0, 0, 0) if v == TRANSPARENT else
                     (((v >> 11) & 0x1F) << 3, ((v >> 5) & 0x3F) << 2, (v & 0x1F) << 3)
                     for v in fr])
        proof.paste(img, ((i % 4) * 64, (i // 4) * 64))
    proof_path = SRC / "contact-sheet.png"
    proof.save(proof_path)
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB) and {proof_path}")


if __name__ == "__main__":
    main()
